sudo: false

language: php
php:
  - hhvm
  - 7
  - 5.6
  - 5.5
  
before_script:
  - composer update --no-interaction

script:
  - mkdir -p logs
  - composer test

after_script:
  - composer coveralls
