sudo: false

language: php
php:
  - hvvm
  - 7
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script:
  - composer update --no-interaction

script:
  - phpunit -c tests/phpunit.xml --coverage-clover build/logs/clover.xml tests

after_script:
  - php ./vendor/bin/coveralls -v