sudo: false

language: php
php:
  - hhvm
  - 7
  - 5.6
  - 5.5

matrix:
  allow_failures:
  - php: 5.5
  
before_script:
  - composer update --no-interaction

script:
  - mkdir -p logs
  - composer.phar test

after_script:
  - composer.phar coveralls
