sudo: false

language: php
php:
  - hhvm
  - 7
  - 5.6

before_script:
  - composer update --no-interaction

script:
  - mkdir -p build/logs
  - phpunit -c tests/phpunit.xml --coverage-clover build/logs/clover.xml tests

after_script:
  - php ./vendor/bin/coveralls -v
